# Create environment using the following command:
# conda env create -f environment.yml

name: gistemp
channels:
  - conda-forge
dependencies:
  # Recommended that xarray is version 2023.7.0 or later
  # (to avoid issues with reading datasets)
  - python=3.11.*
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - requests
    - typing
    - xarray
    - tqdm
    - math
    - itertools